using System.Collections.Immutable;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using CadMcp.Core;

// Usage: CadMcp.CivilSignatures --out <fixture> <release>=<folder with the Civil 3D .NET API assemblies> ...
// Reads assembly metadata only; nothing is loaded or run, so the assemblies of any release work on any machine.
string? output = null;
var releases = new SortedDictionary<string, string>(StringComparer.Ordinal);
var sources = new List<string>();
for (int i = 0; i < args.Length; i++)
{
    if (args[i] == "--out" && i + 1 < args.Length) output = args[++i];
    else if (args[i] == "--source" && i + 1 < args.Length) sources.Add(args[++i]);
    else if (args[i].Split('=', 2) is [var release, var folder] && Directory.Exists(folder)) releases[release] = folder;
    else { Console.Error.WriteLine("Unexpected argument: " + args[i]); return 2; }
}
if (output is null || releases.Count == 0) { Console.Error.WriteLine("Usage: --out <fixture> [--source <note>]... <release>=<folder>..."); return 2; }

// Every type the contract names; their public declared members make the dump of each release.
var types = CivilApiContract.Members.Select(m => m.Split('|')[0]).ToHashSet(StringComparer.Ordinal);
var text = new System.Text.StringBuilder();
text.AppendLine("# Civil 3D managed API signatures of the types CAD MCP calls by reflection, per release: the public members declared");
text.AppendLine("# on each type, M for methods and P for properties without parameter names. A property shows \"get;\" always and");
text.AppendLine("# \"set;\" with a public setter, as the api-probes of HorizunGroup/horizun-civil3d-mcp (Apache License 2.0,");
text.AppendLine("# licenses/horizun-civil3d-mcp-Apache-2.0.txt) print them. For the types both cover, those 2024-2026 probes match these");
text.AppendLine("# sections line for line, except Alignment.CopyToSameSite, which the 2025.2 update added.");
text.AppendLine("# Generated by tests/CadMcp.CivilSignatures (scripts/civil-signatures.ps1) from the metadata of:");
foreach (var source in sources) text.AppendLine("#   " + source);
int status = 0;
foreach (var (release, folder) in releases)
{
    var lines = new SortedSet<string>(StringComparer.Ordinal);
    var found = new HashSet<string>(StringComparer.Ordinal);
    foreach (var dll in Directory.EnumerateFiles(folder, "*.dll").Order(StringComparer.Ordinal))
    {
        using var stream = File.OpenRead(dll);
        using var pe = new PEReader(stream);
        if (!pe.HasMetadata) continue;
        Dump(pe.GetMetadataReader(), types, lines, found);
    }
    foreach (var missing in types.Where(t => !found.Contains(t)).Order(StringComparer.Ordinal))
    { Console.Error.WriteLine(release + ": type not found: " + missing); status = 1; }
    text.AppendLine("[" + release + "]");
    foreach (var line in lines) text.AppendLine(line);
    Console.Error.WriteLine(release + ": " + lines.Count + " members of " + found.Count + " types");
}
if (status == 0) File.WriteAllText(output, text.ToString().Replace("\r\n", "\n"));
return status;

static void Dump(MetadataReader md, HashSet<string> types, SortedSet<string> lines, HashSet<string> found)
{
    var names = new Names();
    foreach (var typeHandle in md.TypeDefinitions)
    {
        var type = md.GetTypeDefinition(typeHandle);
        if (!type.GetDeclaringType().IsNil) continue;
        string full = md.GetString(type.Namespace) + "." + md.GetString(type.Name);
        if (!types.Contains(full)) continue;
        found.Add(full);
        var context = new Generics(type.GetGenericParameters().Select(p => md.GetString(md.GetGenericParameter(p).Name)).ToImmutableArray(), []);
        foreach (var handle in type.GetMethods())
        {
            var method = md.GetMethodDefinition(handle);
            if ((method.Attributes & MethodAttributes.MemberAccessMask) != MethodAttributes.Public) continue;
            if ((method.Attributes & (MethodAttributes.SpecialName | MethodAttributes.RTSpecialName)) != 0) continue;
            var generic = method.GetGenericParameters().Select(p => md.GetString(md.GetGenericParameter(p).Name)).ToImmutableArray();
            var signature = method.DecodeSignature(names, context with { Method = generic });
            string name = md.GetString(method.Name) + (generic.IsEmpty ? "" : "<" + string.Join(",", generic) + ">");
            lines.Add(full + "|M " + ((method.Attributes & MethodAttributes.Static) != 0 ? "static " : "") + signature.ReturnType + " " + name + "(" + string.Join(",", signature.ParameterTypes) + ")");
        }
        foreach (var handle in type.GetProperties())
        {
            var property = md.GetPropertyDefinition(handle);
            var accessors = property.GetAccessors();
            MethodDefinition? Public(MethodDefinitionHandle h)
            {
                if (h.IsNil) return null;
                var accessor = md.GetMethodDefinition(h);
                return (accessor.Attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Public ? accessor : null;
            }
            var getter = Public(accessors.Getter);
            var setter = Public(accessors.Setter);
            if (getter is null && setter is null) continue;
            var any = getter ?? setter!.Value;
            var signature = property.DecodeSignature(names, context);
            string indexer = "";
            if (signature.ParameterTypes.Length > 0)
            {
                // Indexer parameters keep their names, as the published probes show them.
                var parameters = any.GetParameters().Select(md.GetParameter).Where(p => p.SequenceNumber > 0).OrderBy(p => p.SequenceNumber).Select(p => md.GetString(p.Name)).ToArray();
                indexer = "[" + string.Join(", ", signature.ParameterTypes.Select((t, i) => t + " " + (i < parameters.Length ? parameters[i] : "value" + i))) + "]";
            }
            lines.Add(full + "|P " + ((any.Attributes & MethodAttributes.Static) != 0 ? "static " : "") + signature.ReturnType + " " + md.GetString(property.Name) + indexer + " {get;" + (setter is null ? "" : "set;") + "}");
        }
    }
}

internal sealed record Generics(ImmutableArray<string> Type, ImmutableArray<string> Method);

/// <summary>Type names as reflection's Type.Name prints them: no namespace, no generic arity, modifiers dropped.</summary>
internal sealed class Names : ISignatureTypeProvider<string, Generics>
{
    private static string Plain(string name) => name.IndexOf('`') is int tick and >= 0 ? name[..tick] : name;
    public string GetPrimitiveType(PrimitiveTypeCode code) => code.ToString();
    public string GetTypeFromDefinition(MetadataReader reader, TypeDefinitionHandle handle, byte rawTypeKind) => Plain(reader.GetString(reader.GetTypeDefinition(handle).Name));
    public string GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, byte rawTypeKind) => Plain(reader.GetString(reader.GetTypeReference(handle).Name));
    public string GetTypeFromSpecification(MetadataReader reader, Generics context, TypeSpecificationHandle handle, byte rawTypeKind) => reader.GetTypeSpecification(handle).DecodeSignature(this, context);
    public string GetSZArrayType(string element) => element + "[]";
    public string GetArrayType(string element, ArrayShape shape) => element + "[" + new string(',', shape.Rank - 1) + "]";
    public string GetByReferenceType(string element) => element + "&";
    public string GetPointerType(string element) => element + "*";
    public string GetPinnedType(string element) => element;
    public string GetModifiedType(string modifier, string unmodified, bool isRequired) => unmodified;
    public string GetGenericInstantiation(string generic, ImmutableArray<string> arguments) => generic + "<" + string.Join(",", arguments) + ">";
    public string GetGenericTypeParameter(Generics context, int index) => index < context.Type.Length ? context.Type[index] : "T" + index;
    public string GetGenericMethodParameter(Generics context, int index) => index < context.Method.Length ? context.Method[index] : "M" + index;
    public string GetFunctionPointerType(MethodSignature<string> signature) => "IntPtr";
}
